name: 'Build Desktop Universal Binary (macOS)'

inputs:
  upload_artifact:
    description: 'Whether to upload the built artifact'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:

    - name: Calculate cache key suffix
      id: cache-key
      shell: bash
      run: echo "CACHE_KEY_SUFFIX=$(git hash-object desktop-src/CMakeLists.txt)" >> $GITHUB_ENV

    - name: Cache SDL2 source
      uses: actions/cache@v4
      id: cache-sdl2-src
      with:
        path: sdl2-source
        key: sdl2-source-v1

    - name: Cache SDL2 builds
      uses: actions/cache@v4
      id: cache-sdl2-builds
      with:
        path: sdl2-build-universal
        key: sdl2-builds-${{ env.CACHE_KEY_SUFFIX }}
        restore-keys: sdl2-builds-

    - name: Clone SDL2 source if missing
      shell: bash
      if: steps.cache-sdl2-src.outputs.cache-hit != 'true'
      run: git clone -b SDL2 https://github.com/libsdl-org/SDL.git sdl2-source

    - name: Build and install SDL2 for universal binary
      shell: bash
      if: steps.cache-sdl2-builds.outputs.cache-hit != 'true'
      run: |
        mkdir -p ./sdl2-build-universal
        cd ./sdl2-build-universal
        cmake ../sdl2-source \
          -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=./install
        make -j$(nproc)
        make install
        # Verify the build succeeded
        if [ ! -f "./install/lib/libSDL2-2.0.0.dylib" ] && [ ! -f "./install/lib/libSDL2.dylib" ]; then
          echo "SDL2 build failed - no dylib found"
          exit 1
        fi

    # Verify SDL2 dylib exists
    - name: Verify SDL2 build exists
      shell: bash
      run: |
        echo "Checking for SDL2 dylib..."
        if [ -f "./sdl2-build-universal/install/lib/libSDL2-2.0.0.dylib" ]; then
          echo "✓ SDL2 dylib found"
          ls -la "./sdl2-build-universal/install/lib/"
        elif [ -f "./sdl2-build-universal/install/lib/libSDL2.dylib" ]; then
          echo "✓ SDL2 dylib found (generic name)"
          ls -la "./sdl2-build-universal/install/lib/"
        else
          echo "✗ SDL2 dylib NOT found"
          echo "Contents of universal build directory:"
          find "./sdl2-build-universal" -name "*.dylib" 2>/dev/null || echo "No dylibs found"
        fi

    - name: Setup universal SDL2
      shell: bash
      run: |
        mkdir -p ./sdl2-universal/lib
        mkdir -p ./sdl2-universal/include/SDL2

        # Copy the universal SDL2 dylib
        cp ./sdl2-build-universal/install/lib/libSDL2-2.0.0.dylib ./sdl2-universal/lib/libSDL2.dylib

        # Copy SDL2 headers to both expected locations
        # Copy to SDL2/ subdirectory for LVGL
        cp -r ./sdl2-source/include/* ./sdl2-universal/include/SDL2/
        # Also copy to root include for direct access
        cp -r ./sdl2-source/include/* ./sdl2-universal/include/

        echo "SDL2 headers copied to both ./sdl2-universal/include/ and ./sdl2-universal/include/SDL2/"

        # Create additional symlinks for compatibility
        cd ./sdl2-universal/lib
        ln -sf libSDL2.dylib libSDL2-2.0.0.dylib

    - name: Cache CMake build files
      uses: actions/cache@v4
      id: cmake-cache
      with:
        path: desktop-src/build/CMakeFiles
        key: cmake-build-universal-${{ env.CACHE_KEY_SUFFIX }}
        restore-keys: cmake-build-universal-

    - name: Debug directory structure
      shell: bash
      working-directory: desktop-src
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of desktop-src:"
        ls -la
        echo "Looking for CMakeLists.txt files:"
        find . -name "CMakeLists.txt" -exec echo "Found: {}" \; -exec head -3 {} \;

    - name: Build with CMake and Make (universal)
      shell: bash
      working-directory: desktop-src
      run: |
        mkdir -p build
        cd build
        echo "Running cmake with SDL2 paths..."
        echo "SDL2_LIBRARY: $GITHUB_WORKSPACE/sdl2-universal/lib/libSDL2.dylib"
        echo "SDL2_INCLUDE_DIR: $GITHUB_WORKSPACE/sdl2-universal/include"
        ls -la $GITHUB_WORKSPACE/sdl2-universal/lib/
        ls -la $GITHUB_WORKSPACE/sdl2-universal/include/
        cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DSDL2_LIBRARY=$GITHUB_WORKSPACE/sdl2-universal/lib/libSDL2.dylib \
                -DSDL2_INCLUDE_DIR=$GITHUB_WORKSPACE/sdl2-universal/include \
                -DCMAKE_VERBOSE_MAKEFILE=ON
        make VERBOSE=1

    - name: Bundle SDL2 dylib with app and fix paths
      shell: bash
      working-directory: desktop-src/build
      run: |
        # Create Frameworks directory in the app bundle
        mkdir -p main/TactileBrowser.app/Contents/Frameworks

        # Copy SDL2 dylib to the app bundle
        cp ../../sdl2-universal/lib/libSDL2.dylib main/TactileBrowser.app/Contents/Frameworks/

        # Also create the versioned dylib that the app expects
        cd main/TactileBrowser.app/Contents/Frameworks/
        ln -sf libSDL2.dylib libSDL2-2.0.0.dylib

        # Fix the dylib paths in the executable using install_name_tool
        cd ../MacOS
        install_name_tool -change @rpath/libSDL2-2.0.0.dylib @executable_path/../Frameworks/libSDL2-2.0.0.dylib TactileBrowser

        # Verify the changes
        echo "Checking dylib dependencies:"
        otool -L TactileBrowser

    - name: Create distribution directory
      shell: bash
      working-directory: desktop-src/build
      run: |
        mkdir -p ../../dist
        cp -r main/TactileBrowser.app ../../dist/

    - name: Archive macOS app bundle (universal)
      if: inputs.upload_artifact == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: TactileBrowser-macOS-universal
        path: dist/
        compression-level: 6
