name: 'Download Latest SDK'
description: 'Download the latest Tactility SDK artifacts from GitHub Actions'
inputs:
  github-token:
    description: 'GitHub Personal Access Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get latest successful workflow run
      shell: bash
      id: get-run
      run: |
        response=$(curl -s -H "Authorization: token ${{ inputs.github-token }}" \
          "https://api.github.com/repos/NellowTCS/Tactility/actions/workflows/build-sdk.yml/runs?per_page=1&status=success")
        run_id=$(echo $response | jq -r '.workflow_runs[0].id')
        echo "run_id=$run_id" >> $GITHUB_OUTPUT

    - name: Get artifacts
      shell: bash
      run: |
        response=$(curl -s -H "Authorization: token ${{ inputs.github-token }}" \
          "https://api.github.com/repos/NellowTCS/Tactility/actions/runs/${{ steps.get-run.outputs.run_id }}/artifacts")
        echo "$response" > artifacts.json

    - name: Download and unzip TactilitySDK-esp32
      shell: bash
      run: |
        artifacts=$(cat artifacts.json)
        download_url=$(echo $artifacts | jq -r '.artifacts[] | select(.name == "TactilitySDK-esp32") | .archive_download_url')
        if [ -n "$download_url" ]; then
          mkdir -p tactility-src/.tactility/latest-custom-sdk/esp32
          curl -L -H "Authorization: token ${{ inputs.github-token }}" -o temp.zip "$download_url"
          unzip -q temp.zip -d tactility-src/.tactility/latest-custom-sdk/esp32
          rm temp.zip
        else
          echo "TactilitySDK-esp32 not found"
          exit 1
        fi

    - name: Download and unzip TactilitySDK-esp32s3
      shell: bash
      run: |
        artifacts=$(cat artifacts.json)
        download_url=$(echo $artifacts | jq -r '.artifacts[] | select(.name == "TactilitySDK-esp32s3") | .archive_download_url')
        if [ -n "$download_url" ]; then
          mkdir -p tactility-src/.tactility/latest-custom-sdk/esp32s3
          curl -L -H "Authorization: token ${{ inputs.github-token }}" -o temp.zip "$download_url"
          unzip -q temp.zip -d tactility-src/.tactility/latest-custom-sdk/esp32s3
          rm temp.zip
        else
          echo "TactilitySDK-esp32s3 not found"
          exit 1
        fi

    - name: Cleanup
      shell: bash
      run: rm -f artifacts.json