name: 'Build Tactility (ESP-IDF)'
description: Build Tactile Browser for Tactility.

inputs:
  upload_artifact:
    description: 'Whether to upload the built app artifact'
    required: false
    default: 'true'
  use_custom_sdk:
    description: 'Whether to download and use the latest custom SDK'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: 'Download Latest SDK'
      if: inputs.use_custom_sdk == 'true'
      uses: ./.github/actions/download-latest-sdk
      with:
        github-token: ${{ github.token }}
    - name: 'Build with Custom SDK'
      if: inputs.use_custom_sdk == 'true'
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.5
        path: ./tactility-src
        command: export TACTILITY_SDK_PATH=./.tactility && python tactility.py build --local-sdk
    - name: 'Build with Default SDK'
      if: inputs.use_custom_sdk != 'true'
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.5
        path: ./tactility-src
        command: 'python tactility.py build --verbose'
    - name: 'Upload Artifact'
      if: inputs.upload_artifact == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: TactileBrowser_tactility
        path: tactility-src/build/TactileBrowser.app
        retention-days: 30